### ISSUE TITLE
I can't install Chromium 

### ISSUE THREAD

**Issue by Whpitot** [yzane/vscode-markdown-pdf#84]
I can't install Chromium.
Can you help me.

![image](https://user-images.githubusercontent.com/22982803/39864484-49a4fa84-547c-11e8-8846-d9a3205dc661.png)
The error as shown as the above image!
thanks

**Comment by yzane** [comment]
@Whpitot Please use [markdown-pdf.executablePath](https://github.com/yzane/vscode-markdown-pdf#markdown-pdfexecutablepath) option. See [Install](https://github.com/yzane/vscode-markdown-pdf#install)

**Comment by yzane** [comment]
@taoqf 
This is not a markdown-pdf error, it is a chrome error.
What is the distribution you are using?

**Comment by taoqf** [comment]
Version 62.0.3202.89 (Developer Build) built on Debian 9.1, running on Debian 9.4 (64-bit)

**Comment by taoqf** [comment]
I tried `"markdown-pdf.executablePath": "/usr/bin/chromium"` but failed.

**Comment by yzane** [comment]
@taoqf 

This error is another problem than chromium can not install.
I tried with debian 9.4 and the above error occurred.

## google-chrome-stable
Installing "google-chrome-stable" instead of chromium and specifying it with markdown-pdf.executablePath made it possible to convert Markdown file to PDF.

## chromium
In the case of chromium, it can be used by doing the following.
If you use the downloaded chromium, please copy the chrome_sandbox included in it.
```
sudo cp ~/.vscode/extensions/yzane.markdown-pdf-1.2.0/node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome_sandbox /usr/local/sbin/chrome-devel-sandbox
sudo chown root:root /usr/local/sbin/chrome-devel-sandbox
sudo chmod 4755 /usr/local/sbin/chrome-devel-sandbox
```

Put this line in your ~/.bashrc (or .zshenv etc):
```
export CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox
```
See [Linux SUID Sandbox Development](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md)

**Comment by Whpitot** [comment]
@yzane 
I got it.thank you

**Comment by kedarkdr** [comment]
Thanks this helped me

**Comment by kedarkdr** [comment]
> I tried `"markdown-pdf.executablePath": "/usr/bin/chromium"` but failed.

This helped me, thanks

**Comment by phenix3443** [comment]
i meet the same problem, try to remove ~/.vscode/extensions/yzane.markdown-pdf-1.5.0/node_modules/puppeteer-core/.local-chromium/, and open markdown file again, this will install chromium successfully.

**Comment by bugrakeskin** [comment]
> i meet the same problem, try to remove ~/.vscode/extensions/yzane.markdown-pdf-1.5.0/node_modules/puppeteer-core/.local-chromium/, and open markdown file again, this will install chromium successfully.

that worked thank you!! :)
