### ISSUE TITLE
Include local markdown files into PDF

### ISSUE THREAD

**Issue by Sparkenstein** [yzane/vscode-markdown-pdf#86]
This is a very handy plugin thank you for developing it. I have a question about it's usage.
I am including the local markdown files as a link to my README.md. But When I convert the README to PDF, it shows static file links for my markdown files like (file:///c/installation.md) and PDF is just one page. How can I include them into PDF automatically so that it will be a one single pdf. 

Here is my sample README.md:
```
* [Part 1: Installation](installation.md)
* [Part 2: Usage](usage.md)
* [Part 3: Plugins](plugins.md)
* [Part 4: Internationalization](Internationalization.md)
```

It generates only one page PDF with above content and filesystem links to all the md files.

**Comment by gnaeus** [comment]
I've just run into same issue. And I found that it's already solved by [markdown-it-include](https://github.com/camelaissani/markdown-it-include) plugin. And we only need to integrate these two awesome projects.

There is only one little problem: syntax `!!!include(relative-path-to-file.md)!!!` is not very convenient. Since we need a fallback for systems that don't understand these expressions (like GitHub). But there is also another syntax for file inclusions — based on [proposal for CommonMark.org](https://talk.commonmark.org/t/transclusion-or-including-sub-documents-for-reuse/270).  

`:[alternate-text](relative-path-to-file.md)`

So your README.md can look like:

```md
:[Part 1: Installation](installation.md)
:[Part 2: Usage](usage.md)
:[Part 3: Plugins](plugins.md)
:[Part 4: Internationalization](Internationalization.md)
```

In PDF it should be single document that includes contents of all referenced files.  
But GitHub should display only links to another files:

:[Part 1: Installation](installation.md)
:[Part 2: Usage](usage.md)
:[Part 3: Plugins](plugins.md)
:[Part 4: Internationalization](Internationalization.md)

**Comment by goyalyashpal** [comment]
can this issue be closed now?

**Comment by pg-co** [comment]
How do i link into the included content?

```
Example:

included content:
:[Other](other/other.md)

link:
[Other Link](other/other.md#Testing) --> does not work
```

**Comment by Sparkenstein** [comment]
Closing the issue as markdown-include plugin is merged a long ago
